;; This file is autogenerated using vura.holidays.compile/-main

(ns vura.holidays.ae
  (:require 
  [clojure.string]
  [vura.holidays :refer [is-holiday?]]
  [vura.holidays.name :as n]
  [vura.holidays.compiler :as compiler]))


(def holidays
  {"01-01" {"_name" "01-01", :name {:ar "رأس السنة الميلادية"}},
 "12-02" {:name {:en "National Day", :ar "اليوم الوطني"}},
 "1 Muharram" {:name (partial n/get-name "1 Muharram")},
 "1 Shawwal P3D" {:name (partial n/get-name "1 Shawwal")},
 "10 Dhu al-Hijjah P3D"
 {:name (partial n/get-name "10 Dhu al-Hijjah")},
 "27 Rajab" {:name (partial n/get-name "27 Rajab")},
 "1 Ramadan" {:name (partial n/get-name "1 Ramadan")},
 "12 Rabi al-awwal" {:name (partial n/get-name "12 Rabi al-awwal")}}
)


(def locale-holiday-mapping
  (reduce-kv
    (fn [result definition name-mapping]
      (assoc result
             (compiler/compile-type (compiler/parse-definition definition))
             name-mapping))
    nil
    holidays))


(defn holiday?
  [context]
  (some
   (fn [[pred naming]]
     (when (pred context)
       naming))
   locale-holiday-mapping))


(defmethod is-holiday? :ae
  [_ context]
  (holiday? context))