;; This file is autogenerated using vura.holidays.compile/-main

(ns vura.holidays.ar
  (:require 
  [clojure.string]
  [vura.holidays :refer [is-holiday?]]
  [vura.holidays.name :as n]
  [vura.holidays.compiler :as compiler]))


(def holidays
  {"12-08" {:name (partial n/get-name "12-08")},
 "easter -48" {:name (partial n/get-name "easter -48")},
 "04-02"
 {:name
  {:en "Day of the veterans and the fallen in Malvinas War",
   :es "Día del Veterano y de los Caídos en la Guerra de Malvinas"}},
 "01-01" {:name (partial n/get-name "01-01")},
 "substitutes 01-01 if tuesday then previous monday if thursday then next friday"
 {"disable" [2015], :name (partial n/get-name "Bridge Day")},
 "2020-03-30" {:name (partial n/get-name "Bridge Day")},
 "easter -47" {:name (partial n/get-name "easter -47")},
 "12-31 12:00" {"type" "optional", :name (partial n/get-name "12-31")},
 "10-12 if tuesday,wednesday then previous monday if thursday,friday,saturday,sunday then next monday"
 {:name
  {:en "Day of Respect for Cultural Diversity",
   :es "Día del Respeto a la Diversidad Cultural"}},
 "substitutes 12-24 if tuesday then previous monday"
 {:name (partial n/get-name "Bridge Day")},
 "substitutes 10-12 if monday,tuesday,wednesday then previous friday"
 {"disable" [2015 2016 2020], :name (partial n/get-name "Bridge Day")},
 "3rd monday in August"
 {:name
  {:en "Anniversary of the death of General José de San Martín",
   :es "Día del Libertador José de San Martín"}},
 "05-25"
 {:name
  {:en "Day of the First National Government",
   :es "Primer Gobierno Patrio"}},
 "substitutes 06-20 if tuesday then previous monday if thursday then next friday"
 {:name (partial n/get-name "Bridge Day")},
 "substitutes 05-01 if tuesday then previous monday if thursday then next friday"
 {:name (partial n/get-name "Bridge Day")},
 "substitutes 07-09 if tuesday then previous monday if thursday then next friday if saturday then previous friday"
 {"disable" [2015 2022], :name (partial n/get-name "Bridge Day")},
 "11-20 if tuesday,wednesday then previous monday if friday then next monday"
 {:name
  {:en "Day of National Sovereignty",
   :es "Día de la Soberanía nacional"}},
 "easter -2" {:name (partial n/get-name "easter -2")},
 "substitutes 03-24 if tuesday then previous monday if thursday then next friday"
 {:name (partial n/get-name "Bridge Day")},
 "substitutes 04-02 if tuesday then previous monday if thursday then next friday"
 {:name (partial n/get-name "Bridge Day")},
 "substitutes 05-25 if tuesday then previous monday if thursday then next friday"
 {:name (partial n/get-name "Bridge Day")},
 "substitutes 12-08 if tuesday then previous monday if thursday then next friday"
 {:name (partial n/get-name "Bridge Day")},
 "06-20" {:name {:en "National Flag Day", :es "Día de la Bandera"}},
 "05-01" {:name (partial n/get-name "05-01")},
 "easter -3" {:name (partial n/get-name "easter -3")},
 "03-24"
 {:name
  {:en "Day of Remembrance for Truth and Justice",
   :es "Día de la Memoria por la Verdad y la Justicia"}},
 "07-09" {:name (partial n/get-name "Independence Day")},
 "12-24 12:00" {"type" "optional", :name (partial n/get-name "12-24")},
 "substitutes 12-25 if tuesday then previous monday if thursday then next friday"
 {:name (partial n/get-name "Bridge Day")},
 "12-25" {:name (partial n/get-name "12-25")},
 "substitutes 11-20 if saturday,sunday then next monday"
 {"disable" [2016], :name (partial n/get-name "Bridge Day")}}
)


(def locale-holiday-mapping
  (reduce-kv
    (fn [result definition name-mapping]
      (assoc result
             (compiler/compile-type (compiler/parse-definition definition))
             name-mapping))
    nil
    holidays))


(defn holiday?
  [context]
  (some
   (fn [[pred naming]]
     (when (pred context)
       naming))
   locale-holiday-mapping))


(defmethod is-holiday? :ar
  [_ context]
  (holiday? context))