;; This file is autogenerated using vura.holidays.compile/-main

(ns vura.holidays.ax
  (:require 
  [clojure.string]
  [vura.holidays :refer [is-holiday?]]
  [vura.holidays.name :as n]
  [vura.holidays.compiler :as compiler]))


(def holidays
  {"03-30"
 {:name
  {:sv "Ålands demilitariseringsdag", :en "Demilitarization Day"}},
 "01-01" {:name (partial n/get-name "01-01")},
 "easter 39" {:name (partial n/get-name "easter 39")},
 "12-31 12:00" {"type" "bank", :name (partial n/get-name "12-31")},
 "3rd friday after 06-01 12:00"
 {:name {:sv "Midsommarafton", :en "Midsummer Eve"}},
 "easter" {"type" "observance", :name (partial n/get-name "easter")},
 "06-09" {:name {:sv "Självstyrelsedagen", :en "Autonomy Day"}},
 "3rd saturday after 06-01"
 {:name {:sv "Midsommardagen", :en "Midsummer Day"}},
 "easter -2" {:name (partial n/get-name "easter -2")},
 "12-06" {:name (partial n/get-name "Independence Day")},
 "12-26" {:name (partial n/get-name "12-26")},
 "easter 49"
 {"type" "observance", :name (partial n/get-name "easter 49")},
 "easter 1" {:name (partial n/get-name "easter 1")},
 "05-01" {:name (partial n/get-name "05-01")},
 "01-06" {:name (partial n/get-name "01-06")},
 "12-24 12:00" {"type" "bank", :name (partial n/get-name "12-24")},
 "12-25" {:name (partial n/get-name "12-25")}}
)


(def locale-holiday-mapping
  (reduce-kv
    (fn [result definition name-mapping]
      (assoc result
             (compiler/compile-type (compiler/parse-definition definition))
             name-mapping))
    nil
    holidays))


(defn holiday?
  [context]
  (some
   (fn [[pred naming]]
     (when (pred context)
       naming))
   locale-holiday-mapping))


(defmethod is-holiday? :ax
  [_ context]
  (holiday? context))