;; This file is autogenerated using vura.holidays.compile/-main

(ns vura.holidays.bf
  (:require 
  [clojure.string]
  [vura.holidays :refer [is-holiday?]]
  [vura.holidays.name :as n]
  [vura.holidays.compiler :as compiler]))


(def holidays
  {"08-15" {:name (partial n/get-name "08-15")},
 "10 Dhu al-Hijjah" {:name (partial n/get-name "10 Dhu al-Hijjah")},
 "01-01" {:name (partial n/get-name "01-01")},
 "easter 39" {:name (partial n/get-name "easter 39")},
 "11-01" {:name (partial n/get-name "11-01")},
 "easter" {:name (partial n/get-name "easter")},
 "12-11"
 {:name {:fr "Fête nationale", :en "Proclamation of the Republic"}},
 "01-03"
 {:name
  {:fr "Soulèvement populaire",
   :en "Anniversary of the 1966 Upper Voltan coup d'état"}},
 "1 Shawwal" {:name (partial n/get-name "1 Shawwal")},
 "easter 49" {:name (partial n/get-name "easter 49")},
 "easter 1" {:name (partial n/get-name "easter 1")},
 "03-08" {:name (partial n/get-name "03-08")},
 "05-01" {:name (partial n/get-name "05-01")},
 "12 Rabi al-awwal" {:name (partial n/get-name "12 Rabi al-awwal")},
 "08-05" {:name (partial n/get-name "Independence Day")},
 "12-25" {:name (partial n/get-name "12-25")}}
)


(def locale-holiday-mapping
  (reduce-kv
    (fn [result definition name-mapping]
      (assoc result
             (compiler/compile-type (compiler/parse-definition definition))
             name-mapping))
    nil
    holidays))


(defn holiday?
  [context]
  (some
   (fn [[pred naming]]
     (when (pred context)
       naming))
   locale-holiday-mapping))


(defmethod is-holiday? :bf
  [_ context]
  (holiday? context))