;; This file is autogenerated using vura.holidays.compile/-main

(ns vura.holidays.bh
  (:require 
  [clojure.string]
  [vura.holidays :refer [is-holiday?]]
  [vura.holidays.name :as n]
  [vura.holidays.compiler :as compiler]))


(def holidays
  {"12-16" {:name {:ar "اليوم الوطني", :en "National Day"}},
 "01-01" {:name (partial n/get-name "01-01")},
 "12-17" {:name {:ar "يوم الجلوس", :en "Accession Day"}},
 "1 Muharram" {:name (partial n/get-name "1 Muharram")},
 "10 Muharram" {:name (partial n/get-name "10 Muharram")},
 "1 Shawwal" {:name (partial n/get-name "1 Shawwal")},
 "9 Dhu al-Hijjah" {:name (partial n/get-name "9 Dhu al-Hijjah")},
 "10 Dhu al-Hijjah P3D"
 {:name (partial n/get-name "10 Dhu al-Hijjah")},
 "05-01" {"_name" "05-01", :name {:ar "يوم العمال"}},
 "12 Rabi al-awwal" {:name (partial n/get-name "12 Rabi al-awwal")}}
)


(def locale-holiday-mapping
  (reduce-kv
    (fn [result definition name-mapping]
      (assoc result
             (compiler/compile-type (compiler/parse-definition definition))
             name-mapping))
    nil
    holidays))


(defn holiday?
  [context]
  (some
   (fn [[pred naming]]
     (when (pred context)
       naming))
   locale-holiday-mapping))


(defmethod is-holiday? :bh
  [_ context]
  (holiday? context))