;; This file is autogenerated using vura.holidays.compile/-main

(ns vura.holidays.ci
  (:require 
  [clojure.string]
  [vura.holidays :refer [is-holiday?]]
  [vura.holidays.name :as n]
  [vura.holidays.compiler :as compiler]))


(def holidays
  {"08-15" {:name (partial n/get-name "08-15")},
 "10 Dhu al-Hijjah" {:name (partial n/get-name "10 Dhu al-Hijjah")},
 "01-01" {:name (partial n/get-name "01-01")},
 "27 Ramadan" {:name (partial n/get-name "27 Ramadan")},
 "easter 39" {:name (partial n/get-name "easter 39")},
 "08-07 since 1960" {:name (partial n/get-name "Independence Day")},
 "11-01" {:name (partial n/get-name "11-01")},
 "easter 50" {:name (partial n/get-name "easter 50")},
 "1 Shawwal" {:name (partial n/get-name "1 Shawwal")},
 "easter 1" {:name (partial n/get-name "easter 1")},
 "05-01" {:name (partial n/get-name "05-01")},
 "12 Rabi al-awwal" {:name (partial n/get-name "12 Rabi al-awwal")},
 "11-15 since 1996" {:name {:en "National Peace Day"}},
 "12-25" {:name (partial n/get-name "12-25")}}
)


(def locale-holiday-mapping
  (reduce-kv
    (fn [result definition name-mapping]
      (assoc result
             (compiler/compile-type (compiler/parse-definition definition))
             name-mapping))
    nil
    holidays))


(defn holiday?
  [context]
  (some
   (fn [[pred naming]]
     (when (pred context)
       naming))
   locale-holiday-mapping))


(defmethod is-holiday? :ci
  [_ context]
  (holiday? context))