;; This file is autogenerated using vura.holidays.compile/-main

(ns vura.holidays.cu
  (:require 
  [clojure.string]
  [vura.holidays :refer [is-holiday?]]
  [vura.holidays.name :as n]
  [vura.holidays.compiler :as compiler]))


(def holidays
  {"07-25"
 {:name
  {:es "Conmemoración del asalto a Moncada",
   :en
   "Day before the Commemoration of the Assault of the Moncada garrison"}},
 "07-26"
 {:name
  {:es "Día de la Rebeldía Nacional",
   :en "Commemoration of the Assault of the Moncada garrison"}},
 "01-01"
 {:name
  {:es "Triunfo de la Revolución", :en "Triumph of the Revolution"}},
 "01-02"
 {:name
  {:es "Día de Victoria de las Fuerzas Armadas",
   :en "Victory of Armed Forces Day"}},
 "07-27"
 {:name
  {:es "Conmemoración del asalto a Moncada",
   :en
   "Day after the Commemoration of the Assault of the Moncada garrison"}},
 "10-10" {:name (partial n/get-name "Independence Day")},
 "easter -2" {:name (partial n/get-name "easter -2")},
 "05-01" {:name (partial n/get-name "05-01")},
 "12-25" {:name (partial n/get-name "12-25")}}
)


(def locale-holiday-mapping
  (reduce-kv
    (fn [result definition name-mapping]
      (assoc result
             (compiler/compile-type (compiler/parse-definition definition))
             name-mapping))
    nil
    holidays))


(defn holiday?
  [context]
  (some
   (fn [[pred naming]]
     (when (pred context)
       naming))
   locale-holiday-mapping))


(defmethod is-holiday? :cu
  [_ context]
  (holiday? context))