;; This file is autogenerated using vura.holidays.compile/-main

(ns vura.holidays.cx
  (:require 
  [clojure.string]
  [vura.holidays :refer [is-holiday?]]
  [vura.holidays.name :as n]
  [vura.holidays.compiler :as compiler]))


(def holidays
  {"10 Dhu al-Hijjah"
 {"_name" "10 Dhu al-Hijjah", :name {:ms "Hari Raya Haji"}},
 "01-01" {:name (partial n/get-name "01-01")},
 "01-26" {:name {:en "Australia Day"}},
 "10-06" {:name {:en "Territory Day"}},
 "4th monday in March" {:name (partial n/get-name "05-01")},
 "easter -2" {:name (partial n/get-name "easter -2")},
 "1 Shawwal" {"_name" "1 Shawwal", :name {:ms "Hari Raya Puasa"}},
 "12-26" {:name (partial n/get-name "12-26")},
 "chinese 01-0-01 P2D" {:name {:en "Chinese New Year", :zh "春节"}},
 "04-25" {:name {:en "Anzac Day"}},
 "12-25" {:name (partial n/get-name "12-25")}}
)


(def locale-holiday-mapping
  (reduce-kv
    (fn [result definition name-mapping]
      (assoc result
             (compiler/compile-type (compiler/parse-definition definition))
             name-mapping))
    nil
    holidays))


(defn holiday?
  [context]
  (some
   (fn [[pred naming]]
     (when (pred context)
       naming))
   locale-holiday-mapping))


(defmethod is-holiday? :cx
  [_ context]
  (holiday? context))