;; This file is autogenerated using vura.holidays.compile/-main

(ns vura.holidays.dj
  (:require 
  [clojure.string]
  [vura.holidays :refer [is-holiday?]]
  [vura.holidays.name :as n]
  [vura.holidays.compiler :as compiler]))


(def holidays
  {"10 Dhu al-Hijjah" {:name (partial n/get-name "10 Dhu al-Hijjah")},
 "01-01" {:name (partial n/get-name "01-01")},
 "27 Rajab" {:name (partial n/get-name "27 Rajab")},
 "1 Muharram" {:name (partial n/get-name "1 Muharram")},
 "1 Shawwal" {:name (partial n/get-name "1 Shawwal")},
 "9 Dhu al-Hijjah" {:name (partial n/get-name "9 Dhu al-Hijjah")},
 "05-01" {:name (partial n/get-name "05-01")},
 "12 Rabi al-awwal" {:name (partial n/get-name "12 Rabi al-awwal")},
 "06-27 since 1977" {:name (partial n/get-name "Independence Day")},
 "12-25" {:name (partial n/get-name "12-25")}}
)


(def locale-holiday-mapping
  (reduce-kv
    (fn [result definition name-mapping]
      (assoc result
             (compiler/compile-type (compiler/parse-definition definition))
             name-mapping))
    nil
    holidays))


(defn holiday?
  [context]
  (some
   (fn [[pred naming]]
     (when (pred context)
       naming))
   locale-holiday-mapping))


(defmethod is-holiday? :dj
  [_ context]
  (holiday? context))