;; This file is autogenerated using vura.holidays.compile/-main

(ns vura.holidays.eh
  (:require 
  [clojure.string]
  [vura.holidays :refer [is-holiday?]]
  [vura.holidays.name :as n]
  [vura.holidays.compiler :as compiler]))


(def holidays
  {"02-27" {:name (partial n/get-name "Independence Day")},
 "10 Dhu al-Hijjah P2D"
 {:name (partial n/get-name "10 Dhu al-Hijjah")},
 "06-09" {:name {:en "Day of the Martyrs"}},
 "1 Muharram" {:name (partial n/get-name "1 Muharram")},
 "05-10" {:name {:en "May 20 Revolution"}},
 "03-08" {:name {:en "First Martyr"}},
 "12 Rabi al-awwal" {:name (partial n/get-name "12 Rabi al-awwal")},
 "1 Shawwal P2D" {:name (partial n/get-name "1 Shawwal")},
 "06-17" {:name {:en "Day of National Unity"}}}
)


(def locale-holiday-mapping
  (reduce-kv
    (fn [result definition name-mapping]
      (assoc result
             (compiler/compile-type (compiler/parse-definition definition))
             name-mapping))
    nil
    holidays))


(defn holiday?
  [context]
  (some
   (fn [[pred naming]]
     (when (pred context)
       naming))
   locale-holiday-mapping))


(defmethod is-holiday? :eh
  [_ context]
  (holiday? context))