;; This file is autogenerated using vura.holidays.compile/-main

(ns vura.holidays.fi
  (:require 
  [clojure.string]
  [vura.holidays :refer [is-holiday?]]
  [vura.holidays.name :as n]
  [vura.holidays.compiler :as compiler]))


(def holidays
  {"01-01" {:name (partial n/get-name "01-01")},
 "easter 39" {:name (partial n/get-name "easter 39")},
 "2nd sunday in November"
 {"type" "observance", :name (partial n/get-name "Fathers Day")},
 "easter" {:name (partial n/get-name "easter")},
 "12-31 14:00 if sunday then 00:00"
 {"type" "bank", :name (partial n/get-name "12-31")},
 "12-24" {"type" "bank", :name (partial n/get-name "12-24")},
 "friday after 06-19"
 {"type" "bank",
  :name
  {:fi "Juhannusaatto", :en "Midsummer Eve", :sv "Midsommarafton"}},
 "easter -2" {:name (partial n/get-name "easter -2")},
 "2nd sunday in May"
 {"type" "observance", :name (partial n/get-name "Mothers Day")},
 "12-06" {:name (partial n/get-name "Independence Day")},
 "12-26" {:name (partial n/get-name "12-26")},
 "easter 49" {:name (partial n/get-name "easter 49")},
 "easter 1" {:name (partial n/get-name "easter 1")},
 "05-01" {:name (partial n/get-name "05-01")},
 "saturday after 06-20"
 {:name
  {:fi "Juhannuspäivä", :en "Midsummer Day", :sv "Midsommardagen"}},
 "01-06" {:name (partial n/get-name "01-06")},
 "saturday after 10-31" {:name (partial n/get-name "11-01")},
 "12-25" {:name (partial n/get-name "12-25")}}
)


(def locale-holiday-mapping
  (reduce-kv
    (fn [result definition name-mapping]
      (assoc result
             (compiler/compile-type (compiler/parse-definition definition))
             name-mapping))
    nil
    holidays))


(defn holiday?
  [context]
  (some
   (fn [[pred naming]]
     (when (pred context)
       naming))
   locale-holiday-mapping))


(defmethod is-holiday? :fi
  [_ context]
  (holiday? context))