;; This file is autogenerated using vura.holidays.compile/-main

(ns vura.holidays.gu
  (:require 
  [clojure.string]
  [vura.holidays :refer [is-holiday?]]
  [vura.holidays.name :as n]
  [vura.holidays.compiler :as compiler]))


(def holidays
  {"1st monday in March"
 {:name {:en "Guam History and Chamorro Heritage Day"}},
 "easter -2"
 {"type" "observance", :name (partial n/get-name "easter -2")},
 "07-21 if sunday then next monday" {:name {:en "Liberation Day"}},
 "11-02" {:name (partial n/get-name "11-02")},
 "12-08 if sunday then next monday"
 {:name {:en "Our Lady of Camarin Day"}}}
)


(def locale-holiday-mapping
  (reduce-kv
    (fn [result definition name-mapping]
      (assoc result
             (compiler/compile-type (compiler/parse-definition definition))
             name-mapping))
    nil
    holidays))


(defn holiday?
  [context]
  (some
   (fn [[pred naming]]
     (when (pred context)
       naming))
   locale-holiday-mapping))


(defmethod is-holiday? :gu
  [_ context]
  (holiday? context))