;; This file is autogenerated using vura.holidays.compile/-main

(ns vura.holidays.hk
  (:require 
  [clojure.string]
  [vura.holidays :refer [is-holiday?]]
  [vura.holidays.name :as n]
  [vura.holidays.compiler :as compiler]))


(def holidays
  {"01-01 and if Sunday then next Monday"
 {"substitute" true, "_name" "01-01", :name {:zh "一月一日"}},
 "12-26 and if Sunday then next Monday if Monday then next Tuesday"
 {"substitute" true,
  :name
  {:en "The first weekday after Christmas Day", :zh "圣诞节后的第一个工作日"}},
 "07-01 and if Sunday then next Monday"
 {"substitute" true,
  :name
  {:en "Hong Kong Special Administrative Region Establishment Day",
   :zh "香港特別行政區成立紀念日"}},
 "easter -1" {:name (partial n/get-name "easter -1")},
 "chinese 08-0-16 and if Sunday then next Monday if is public holiday then next day omit Saturday, Sunday"
 {"substitute" true,
  :name
  {:en "The day following the Chinese Mid-Autumn Festival",
   :zh "中秋節翌日"}},
 "easter" {:name (partial n/get-name "easter")},
 "chinese 01-0-03 and if Saturday then next Monday"
 {:name {:en "The third day of the Lunar New Year", :zh "農曆年初三"}},
 "chinese 01-0-02 and if Saturday then next Monday"
 {:name {:en "The second day of the Lunar New Year", :zh "農曆年初二"}},
 "easter -2" {:name (partial n/get-name "easter -2")},
 "chinese 5-01 solarterm and if Sunday then next Monday"
 {:name {:en "Qingming Festival", :zh "清明節"}},
 "easter 1"
 {"disable" ["2021-04-05"],
  "enable" ["2021-04-06"],
  :name (partial n/get-name "easter 1")},
 "12-25 and if Sunday then next Monday"
 {"substitute" true, :name (partial n/get-name "12-25")},
 "05-01 and if Sunday then next Monday"
 {"substitute" true, :name (partial n/get-name "05-01")},
 "chinese 04-0-08 and if Sunday then next Monday"
 {:name {:en "Birthday of the Buddha", :zh "佛誕"}},
 "chinese 01-0-01 and if Saturday then next Tuesday"
 {:name {:en "Lunar New Year", :zh "農曆年初一"}},
 "chinese 09-0-09 and if Sunday then next Monday"
 {"substitute" true, :name {:en "Chung Yeung Festival", :zh "重阳节"}},
 "chinese 05-0-05" {:name {:en "Dragon Boat Festival", :zh "端午节"}},
 "10-01 and if Sunday then next Monday"
 {"substitute" true, :name {:en "National Day", :zh "國慶日"}}}
)


(def locale-holiday-mapping
  (reduce-kv
    (fn [result definition name-mapping]
      (assoc result
             (compiler/compile-type (compiler/parse-definition definition))
             name-mapping))
    nil
    holidays))


(defn holiday?
  [context]
  (some
   (fn [[pred naming]]
     (when (pred context)
       naming))
   locale-holiday-mapping))


(defmethod is-holiday? :hk
  [_ context]
  (holiday? context))