;; This file is autogenerated using vura.holidays.compile/-main

(ns vura.holidays.im
  (:require 
  [clojure.string]
  [vura.holidays :refer [is-holiday?]]
  [vura.holidays.name :as n]
  [vura.holidays.compiler :as compiler]))


(def holidays
  {"2nd friday in June" {:name {:en "Tourist Trophy, Senior Race Day"}},
 "07-05" {:name {:en "Tynwald Day"}}}
)


(def locale-holiday-mapping
  (reduce-kv
    (fn [result definition name-mapping]
      (assoc result
             (compiler/compile-type (compiler/parse-definition definition))
             name-mapping))
    nil
    holidays))


(defn holiday?
  [context]
  (some
   (fn [[pred naming]]
     (when (pred context)
       naming))
   locale-holiday-mapping))


(defmethod is-holiday? :im
  [_ context]
  (holiday? context))