;; This file is autogenerated using vura.holidays.compile/-main

(ns vura.holidays.it
  (:require 
  [clojure.string]
  [vura.holidays :refer [is-holiday?]]
  [vura.holidays.name :as n]
  [vura.holidays.compiler :as compiler]))


(def holidays
  {"12-08" {:name (partial n/get-name "12-08")},
 "08-15" {:name (partial n/get-name "08-15")},
 "01-01" {:name (partial n/get-name "01-01")},
 "06-02" {:name {:it "Festa della Repubblica", :en "Republic Day"}},
 "11-01" {:name (partial n/get-name "11-01")},
 "easter" {:name (partial n/get-name "easter")},
 "2nd sunday in May"
 {"type" "observance", :name (partial n/get-name "Mothers Day")},
 "2011-03-17"
 {:name {:it "Festa Nazionale 2011", :en "National Day 2011"}},
 "12-26" {:name (partial n/get-name "12-26")},
 "easter 1" {:name (partial n/get-name "easter 1")},
 "05-01" {:name (partial n/get-name "05-01")},
 "01-06" {:name (partial n/get-name "01-06")},
 "04-25"
 {:name {:it "Anniversario della Liberazione", :en "Liberation Day"}},
 "12-25" {:name (partial n/get-name "12-25")}}
)


(def locale-holiday-mapping
  (reduce-kv
    (fn [result definition name-mapping]
      (assoc result
             (compiler/compile-type (compiler/parse-definition definition))
             name-mapping))
    nil
    holidays))


(defn holiday?
  [context]
  (some
   (fn [[pred naming]]
     (when (pred context)
       naming))
   locale-holiday-mapping))


(defmethod is-holiday? :it
  [_ context]
  (holiday? context))