;; This file is autogenerated using vura.holidays.compile/-main

(ns vura.holidays.jm
  (:require 
  [clojure.string]
  [vura.holidays :refer [is-holiday?]]
  [vura.holidays.name :as n]
  [vura.holidays.compiler :as compiler]))


(def holidays
  {"easter -46" {:name (partial n/get-name "easter -46")},
 "08-06 and if sunday then next monday"
 {"substitute" true, :name (partial n/get-name "Independence Day")},
 "12-25 and if sunday then next tuesday"
 {"substitute" true, :name (partial n/get-name "12-25")},
 "01-01 and if sunday then next monday"
 {"substitute" true, :name (partial n/get-name "01-01")},
 "easter" {"type" "observance", :name (partial n/get-name "easter")},
 "3rd monday in October" {:name {:en "National Heroes Day"}},
 "easter -2" {:name (partial n/get-name "easter -2")},
 "12-26 and if sunday then next monday"
 {"substitute" true, :name (partial n/get-name "12-26")},
 "easter 1" {:name (partial n/get-name "easter 1")},
 "05-23 if saturday,sunday then next monday"
 {:name (partial n/get-name "05-01")},
 "08-01 if sunday then next monday" {:name {:en "Emancipation Day"}}}
)


(def locale-holiday-mapping
  (reduce-kv
    (fn [result definition name-mapping]
      (assoc result
             (compiler/compile-type (compiler/parse-definition definition))
             name-mapping))
    nil
    holidays))


(defn holiday?
  [context]
  (some
   (fn [[pred naming]]
     (when (pred context)
       naming))
   locale-holiday-mapping))


(defmethod is-holiday? :jm
  [_ context]
  (holiday? context))