;; This file is autogenerated using vura.holidays.compile/-main

(ns vura.holidays.km
  (:require 
  [clojure.string]
  [vura.holidays :refer [is-holiday?]]
  [vura.holidays.name :as n]
  [vura.holidays.compiler :as compiler]))


(def holidays
  {"03-18"
 {:name
  {:fr "Journée de Cheikh Al Maarouf", :en "Cheikh Al Maarouf Day"}},
 "01-01" {:name (partial n/get-name "01-01")},
 "27 Rajab" {:name (partial n/get-name "27 Rajab")},
 "10 Dhu al-Hijjah P2DT0H0M"
 {:name (partial n/get-name "10 Dhu al-Hijjah")},
 "1 Muharram" {:name (partial n/get-name "1 Muharram")},
 "07-06" {:name (partial n/get-name "Independence Day")},
 "11-12" {:name {:fr "Journée Maoré", :en "Maore Day"}},
 "05-01" {:name (partial n/get-name "05-01")},
 "12 Rabi al-awwal" {:name (partial n/get-name "12 Rabi al-awwal")},
 "1 Shawwal P3DT0H0M" {:name (partial n/get-name "1 Shawwal")}}
)


(def locale-holiday-mapping
  (reduce-kv
    (fn [result definition name-mapping]
      (assoc result
             (compiler/compile-type (compiler/parse-definition definition))
             name-mapping))
    nil
    holidays))


(defn holiday?
  [context]
  (some
   (fn [[pred naming]]
     (when (pred context)
       naming))
   locale-holiday-mapping))


(defmethod is-holiday? :km
  [_ context]
  (holiday? context))