;; This file is autogenerated using vura.holidays.compile/-main

(ns vura.holidays.kn
  (:require 
  [clojure.string]
  [vura.holidays :refer [is-holiday?]]
  [vura.holidays.name :as n]
  [vura.holidays.compiler :as compiler]))


(def holidays
  {"09-19 if Sunday then next Monday"
 {"substitute" true, :name (partial n/get-name "Independence Day")},
 "01-01 and if Saturday then next Monday"
 {"substitute" true, :name (partial n/get-name "01-01")},
 "1st Monday in May" {:name (partial n/get-name "05-01")},
 "01-02" {:name {:en "Carnival Day"}},
 "09-16 and if Sunday then next Monday"
 {"substitute" true, :name {:en "National Heroes' Day"}},
 "easter 50" {:name (partial n/get-name "easter 50")},
 "1st Tuesday in August" {:name {:en "Culturama Day"}},
 "easter" {"type" "observance", :name (partial n/get-name "easter")},
 "easter -2" {:name (partial n/get-name "easter -2")},
 "12-26" {:name (partial n/get-name "12-26")},
 "easter 49"
 {"type" "observance", :name (partial n/get-name "easter 49")},
 "easter 1" {:name (partial n/get-name "easter 1")},
 "1st Monday in August" {:name {:en "Emancipation Day"}},
 "12-25" {:name (partial n/get-name "12-25")}}
)


(def locale-holiday-mapping
  (reduce-kv
    (fn [result definition name-mapping]
      (assoc result
             (compiler/compile-type (compiler/parse-definition definition))
             name-mapping))
    nil
    holidays))


(defn holiday?
  [context]
  (some
   (fn [[pred naming]]
     (when (pred context)
       naming))
   locale-holiday-mapping))


(defmethod is-holiday? :kn
  [_ context]
  (holiday? context))