;; This file is autogenerated using vura.holidays.compile/-main

(ns vura.holidays.lu
  (:require 
  [clojure.string]
  [vura.holidays :refer [is-holiday?]]
  [vura.holidays.name :as n]
  [vura.holidays.compiler :as compiler]))


(def holidays
  {"08-15" {:name (partial n/get-name "08-15")},
 "01-01" {:name (partial n/get-name "01-01")},
 "easter 39" {:name (partial n/get-name "easter 39")},
 "05-09"
 {"active" [{"from" "2019-01-01"}],
  :name (partial n/get-name "05-09")},
 "11-01" {:name (partial n/get-name "11-01")},
 "easter 50" {:name (partial n/get-name "easter 50")},
 "easter" {"type" "observance", :name (partial n/get-name "easter")},
 "06-23" {:name {:fr "L’anniversaire du Grand-Duc"}},
 "easter -2"
 {"type" "observance", :name (partial n/get-name "easter -2")},
 "12-26" {:name (partial n/get-name "12-26")},
 "easter 1" {:name (partial n/get-name "easter 1")},
 "05-01" {"_name" "05-01", :name {:fr "1er mai"}},
 "12-25" {:name (partial n/get-name "12-25")}}
)


(def locale-holiday-mapping
  (reduce-kv
    (fn [result definition name-mapping]
      (assoc result
             (compiler/compile-type (compiler/parse-definition definition))
             name-mapping))
    nil
    holidays))


(defn holiday?
  [context]
  (some
   (fn [[pred naming]]
     (when (pred context)
       naming))
   locale-holiday-mapping))


(defmethod is-holiday? :lu
  [_ context]
  (holiday? context))