;; This file is autogenerated using vura.holidays.compile/-main

(ns vura.holidays.ly
  (:require 
  [clojure.string]
  [vura.holidays :refer [is-holiday?]]
  [vura.holidays.name :as n]
  [vura.holidays.compiler :as compiler]))


(def holidays
  {"10-23" {:name (partial n/get-name "Liberation Day")},
 "09-16" {:name {:ar "يوم الشهداء", :en "Martyrs' Day"}},
 "12-24" {:name (partial n/get-name "Independence Day")},
 "02-17" {:name (partial n/get-name "Revolution Day")},
 "1 Muharram" {:name (partial n/get-name "1 Muharram")},
 "1 Shawwal P3D" {:name (partial n/get-name "1 Shawwal")},
 "9 Dhu al-Hijjah" {:name (partial n/get-name "9 Dhu al-Hijjah")},
 "10 Dhu al-Hijjah P3D"
 {:name (partial n/get-name "10 Dhu al-Hijjah")},
 "05-01" {:name (partial n/get-name "05-01")},
 "12 Rabi al-awwal" {:name (partial n/get-name "12 Rabi al-awwal")}}
)


(def locale-holiday-mapping
  (reduce-kv
    (fn [result definition name-mapping]
      (assoc result
             (compiler/compile-type (compiler/parse-definition definition))
             name-mapping))
    nil
    holidays))


(defn holiday?
  [context]
  (some
   (fn [[pred naming]]
     (when (pred context)
       naming))
   locale-holiday-mapping))


(defmethod is-holiday? :ly
  [_ context]
  (holiday? context))