;; This file is autogenerated using vura.holidays.compile/-main

(ns vura.holidays.ml
  (:require 
  [clojure.string]
  [vura.holidays :refer [is-holiday?]]
  [vura.holidays.name :as n]
  [vura.holidays.compiler :as compiler]))


(def holidays
  {"03-26" {:name {:fr "Journée des Martyrs", :en "Martyrs' Day"}},
 "10 Dhu al-Hijjah" {:name (partial n/get-name "10 Dhu al-Hijjah")},
 "01-01" {:name (partial n/get-name "01-01")},
 "01-20" {:name {:fr "Fête de l'armée", :en "Army Day"}},
 "05-25" {:name "Jour de l'Afrique"},
 "1 Shawwal" {:name (partial n/get-name "1 Shawwal")},
 "easter 1" {:name (partial n/get-name "easter 1")},
 "05-01" {:name (partial n/get-name "05-01")},
 "09-22"
 {"_name" "Independence Day",
  :name {:fr "Fête nationale de l'indépendance"}},
 "12 Rabi al-awwal" {:name (partial n/get-name "12 Rabi al-awwal")},
 "12-25" {:name (partial n/get-name "12-25")}}
)


(def locale-holiday-mapping
  (reduce-kv
    (fn [result definition name-mapping]
      (assoc result
             (compiler/compile-type (compiler/parse-definition definition))
             name-mapping))
    nil
    holidays))


(defn holiday?
  [context]
  (some
   (fn [[pred naming]]
     (when (pred context)
       naming))
   locale-holiday-mapping))


(defmethod is-holiday? :ml
  [_ context]
  (holiday? context))