;; This file is autogenerated using vura.holidays.compile/-main

(ns vura.holidays.mr
  (:require 
  [clojure.string]
  [vura.holidays :refer [is-holiday?]]
  [vura.holidays.name :as n]
  [vura.holidays.compiler :as compiler]))


(def holidays
  {"01-01" {:name (partial n/get-name "01-01")},
 "05-01" {:name (partial n/get-name "05-01")},
 "05-25" {:name {:ar "يوم افريقيا", :en "Africa Day"}},
 "11-28" {:name (partial n/get-name "Independence Day")},
 "1 Muharram" {:name (partial n/get-name "1 Muharram")},
 "12 Rabi al-awwal" {:name (partial n/get-name "12 Rabi al-awwal")},
 "1 Shawwal" {:name (partial n/get-name "1 Shawwal")},
 "10 Dhu al-Hijjah P3D" {:name (partial n/get-name "10 Dhu al-Hijjah")}}
)


(def locale-holiday-mapping
  (reduce-kv
    (fn [result definition name-mapping]
      (assoc result
             (compiler/compile-type (compiler/parse-definition definition))
             name-mapping))
    nil
    holidays))


(defn holiday?
  [context]
  (some
   (fn [[pred naming]]
     (when (pred context)
       naming))
   locale-holiday-mapping))


(defmethod is-holiday? :mr
  [_ context]
  (holiday? context))