;; This file is autogenerated using vura.holidays.compile/-main

(ns vura.holidays.mx
  (:require 
  [clojure.string]
  [vura.holidays :refer [is-holiday?]]
  [vura.holidays.name :as n]
  [vura.holidays.compiler :as compiler]))


(def holidays
  {"3rd monday in November"
 {:name
  {:en "Revolution Day (day off)",
   :es "Día de la Revolución (día libre)"}},
 "11-20" {:name (partial n/get-name "Revolution Day")},
 "01-01" {:name (partial n/get-name "01-01")},
 "12-01 every 6 years since 1934"
 {:name
  {:en "Change of Federal Government",
   :es "Transmisión del Poder Ejecutivo Federal"}},
 "1st monday in February"
 {:name
  {:en "Constitution Day (day off)",
   :es "Día de la Constitución (día libre)"}},
 "09-16" {:name (partial n/get-name "Independence Day")},
 "easter -2" {"type" "bank", :name (partial n/get-name "easter -2")},
 "02-05" {:name (partial n/get-name "Constitution Day")},
 "05-10"
 {"type" "observance", :name (partial n/get-name "Mothers Day")},
 "11-02" {"type" "bank", :name (partial n/get-name "11-02")},
 "05-01" {:name (partial n/get-name "05-01")},
 "easter -3" {"type" "bank", :name (partial n/get-name "easter -3")},
 "3rd monday in March"
 {:name
  {:en "Benito Juárez's birthday (day off)",
   :es "Natalicio de Benito Juárez (día libre)"}},
 "03-21"
 {:name
  {:en "Benito Juárez's birthday", :es "Natalicio de Benito Juárez"}},
 "12-25" {:name (partial n/get-name "12-25")},
 "12-12"
 {"type" "bank",
  :name
  {:en "Day of the Virgin of Guadalupe",
   :es "Día de la Virgen de Guadalupe"}}}
)


(def locale-holiday-mapping
  (reduce-kv
    (fn [result definition name-mapping]
      (assoc result
             (compiler/compile-type (compiler/parse-definition definition))
             name-mapping))
    nil
    holidays))


(defn holiday?
  [context]
  (some
   (fn [[pred naming]]
     (when (pred context)
       naming))
   locale-holiday-mapping))


(defmethod is-holiday? :mx
  [_ context]
  (holiday? context))