;; This file is autogenerated using vura.holidays.compile/-main

(ns vura.holidays.ne
  (:require 
  [clojure.string]
  [vura.holidays :refer [is-holiday?]]
  [vura.holidays.name :as n]
  [vura.holidays.compiler :as compiler]))


(def holidays
  {"10 Dhu al-Hijjah" {:name (partial n/get-name "10 Dhu al-Hijjah")},
 "01-01" {:name (partial n/get-name "01-01")},
 "27 Ramadan" {:name (partial n/get-name "27 Ramadan")},
 "12-18"
 {:name {:fr "Proclamation de la République", :en "Republic Day"}},
 "08-03"
 {"_name" "Independence Day",
  :name {:fr "Proclamation de l'indépendance"}},
 "1 Muharram" {:name (partial n/get-name "1 Muharram")},
 "1 Shawwal" {:name (partial n/get-name "1 Shawwal")},
 "easter 1" {:name (partial n/get-name "easter 1")},
 "05-01" {:name (partial n/get-name "05-01")},
 "04-24"
 {:name {:fr "Journée Nationale de la Concorde", :en "Concord Day"}},
 "12 Rabi al-awwal" {:name (partial n/get-name "12 Rabi al-awwal")},
 "12-25" {:name (partial n/get-name "12-25")}}
)


(def locale-holiday-mapping
  (reduce-kv
    (fn [result definition name-mapping]
      (assoc result
             (compiler/compile-type (compiler/parse-definition definition))
             name-mapping))
    nil
    holidays))


(defn holiday?
  [context]
  (some
   (fn [[pred naming]]
     (when (pred context)
       naming))
   locale-holiday-mapping))


(defmethod is-holiday? :ne
  [_ context]
  (holiday? context))