;; This file is autogenerated using vura.holidays.compile/-main

(ns vura.holidays.pe
  (:require 
  [clojure.string]
  [vura.holidays :refer [is-holiday?]]
  [vura.holidays.name :as n]
  [vura.holidays.compiler :as compiler]))


(def holidays
  {"12-08" {:name (partial n/get-name "12-08")},
 "01-01" {:name (partial n/get-name "01-01")},
 "06-29" {:name (partial n/get-name "06-29")},
 "11-01" {:name (partial n/get-name "11-01")},
 "10-08" {:name {:en "Battle of Angamos", :es "Combate de Angamos"}},
 "easter" {:name (partial n/get-name "easter")},
 "easter -2" {:name (partial n/get-name "easter -2")},
 "08-30"
 {:name {:en "Santa Rosa de Lima", :es "Día de Santa Rosa de Lima"}},
 "07-29" {:name (partial n/get-name "Independence Day")},
 "05-01" {:name (partial n/get-name "05-01")},
 "easter -3" {:name (partial n/get-name "easter -3")},
 "07-28" {:name (partial n/get-name "Independence Day")},
 "12-25" {:name (partial n/get-name "12-25")}}
)


(def locale-holiday-mapping
  (reduce-kv
    (fn [result definition name-mapping]
      (assoc result
             (compiler/compile-type (compiler/parse-definition definition))
             name-mapping))
    nil
    holidays))


(defn holiday?
  [context]
  (some
   (fn [[pred naming]]
     (when (pred context)
       naming))
   locale-holiday-mapping))


(defmethod is-holiday? :pe
  [_ context]
  (holiday? context))