;; This file is autogenerated using vura.holidays.compile/-main

(ns vura.holidays.ro
  (:require 
  [clojure.string]
  [vura.holidays :refer [is-holiday?]]
  [vura.holidays.name :as n]
  [vura.holidays.compiler :as compiler]))


(def holidays
  {"12-08"
 {"type" "observance", :name (partial n/get-name "Constitution Day")},
 "08-15" {:name (partial n/get-name "08-15")},
 "06-01" {:name {:ro "Ziua Copilului", :en "Children's Day"}},
 "1st sunday in May"
 {"type" "observance", :name (partial n/get-name "Mothers Day")},
 "orthodox 49" {:name (partial n/get-name "easter 49")},
 "01-01" {:name (partial n/get-name "01-01")},
 "orthodox 39"
 {"type" "observance", :name (partial n/get-name "easter 39")},
 "01-24" {:name {:ro "Ziua Unirii", :en "Unification Day"}},
 "orthodox 50" {:name (partial n/get-name "easter 50")},
 "12-01"
 {:name
  {:ro "Ziua națională, Ziua Marii Uniri", :en "National holiday"}},
 "12-26" {:name (partial n/get-name "12-26")},
 "orthodox -2" {:name (partial n/get-name "easter -2")},
 "03-08" {"type" "observance", :name {:ro "Ziua Mamei"}},
 "11-30" {:name {:ro "Sfântul Andrei", :en "St Andrew's Day"}},
 "07-29"
 {"type" "observance",
  :name {:ro "Ziua Imnului național", :en "National Anthem Day"}},
 "05-01" {:name (partial n/get-name "05-01")},
 "orthodox" {:name (partial n/get-name "easter")},
 "06-26"
 {"type" "observance",
  :name {:ro "Ziua drapelului national", :en "Flag Day"}},
 "orthodox 1" {:name (partial n/get-name "easter 1")},
 "12-25" {:name (partial n/get-name "12-25")}}
)


(def locale-holiday-mapping
  (reduce-kv
    (fn [result definition name-mapping]
      (assoc result
             (compiler/compile-type (compiler/parse-definition definition))
             name-mapping))
    nil
    holidays))


(defn holiday?
  [context]
  (some
   (fn [[pred naming]]
     (when (pred context)
       naming))
   locale-holiday-mapping))


(defmethod is-holiday? :ro
  [_ context]
  (holiday? context))