;; This file is autogenerated using vura.holidays.compile/-main

(ns vura.holidays.sc
  (:require 
  [clojure.string]
  [vura.holidays :refer [is-holiday?]]
  [vura.holidays.name :as n]
  [vura.holidays.compiler :as compiler]))


(def holidays
  {"12-08" {:name (partial n/get-name "12-08")},
 "08-15" {:name (partial n/get-name "08-15")},
 "easter 60" {:name (partial n/get-name "easter 60")},
 "06-29" {:name (partial n/get-name "Independence Day")},
 "06-18" {:name (partial n/get-name "National Holiday")},
 "11-01" {:name (partial n/get-name "11-01")},
 "easter -1" {:name (partial n/get-name "easter -1")},
 "easter" {:name (partial n/get-name "easter")},
 "easter -2" {:name (partial n/get-name "easter -2")},
 "01-01 P2D" {:name (partial n/get-name "01-01")},
 "easter 1" {:name (partial n/get-name "easter 1")},
 "05-01" {:name (partial n/get-name "05-01")},
 "12-25" {:name (partial n/get-name "12-25")}}
)


(def locale-holiday-mapping
  (reduce-kv
    (fn [result definition name-mapping]
      (assoc result
             (compiler/compile-type (compiler/parse-definition definition))
             name-mapping))
    nil
    holidays))


(defn holiday?
  [context]
  (some
   (fn [[pred naming]]
     (when (pred context)
       naming))
   locale-holiday-mapping))


(defmethod is-holiday? :sc
  [_ context]
  (holiday? context))