;; This file is autogenerated using vura.holidays.compile/-main

(ns vura.holidays.sd
  (:require 
  [clojure.string]
  [vura.holidays :refer [is-holiday?]]
  [vura.holidays.name :as n]
  [vura.holidays.compiler :as compiler]))


(def holidays
  {"01-01" {:name (partial n/get-name "Independence Day")},
 "12-19" {:name (partial n/get-name "Revolution Day")},
 "1 Muharram" {:name (partial n/get-name "1 Muharram")},
 "10 Dhu al-Hijjah P3D"
 {:name (partial n/get-name "10 Dhu al-Hijjah")},
 "julian 12-25"
 {"_name" "julian 12-25", :name {:en "Coptic Christmas"}},
 "orthodox" {"_name" "orthodox", :name {:en "Coptic Easter"}},
 "1 Shawwal P4D" {:name (partial n/get-name "1 Shawwal")},
 "12 Rabi al-awwal" {:name (partial n/get-name "12 Rabi al-awwal")},
 "12-25" {:name (partial n/get-name "12-25")}}
)


(def locale-holiday-mapping
  (reduce-kv
    (fn [result definition name-mapping]
      (assoc result
             (compiler/compile-type (compiler/parse-definition definition))
             name-mapping))
    nil
    holidays))


(defn holiday?
  [context]
  (some
   (fn [[pred naming]]
     (when (pred context)
       naming))
   locale-holiday-mapping))


(defmethod is-holiday? :sd
  [_ context]
  (holiday? context))