;; This file is autogenerated using vura.holidays.compile/-main

(ns vura.holidays.so
  (:require 
  [clojure.string]
  [vura.holidays :refer [is-holiday?]]
  [vura.holidays.name :as n]
  [vura.holidays.compiler :as compiler]))


(def holidays
  {"01-01" {:name (partial n/get-name "01-01")},
 "05-01" {:name (partial n/get-name "05-01")},
 "06-26"
 {:name
  {:ar "استقلال الصومال البريطاني",
   :en "Independence of British Somaliland"}},
 "07-01" {:name (partial n/get-name "Independence Day")},
 "10 Muharram" {:name (partial n/get-name "10 Muharram")},
 "12 Rabi al-awwal" {:name (partial n/get-name "12 Rabi al-awwal")},
 "1 Shawwal" {:name (partial n/get-name "1 Shawwal")},
 "10 Dhu al-Hijjah" {:name (partial n/get-name "10 Dhu al-Hijjah")}}
)


(def locale-holiday-mapping
  (reduce-kv
    (fn [result definition name-mapping]
      (assoc result
             (compiler/compile-type (compiler/parse-definition definition))
             name-mapping))
    nil
    holidays))


(defn holiday?
  [context]
  (some
   (fn [[pred naming]]
     (when (pred context)
       naming))
   locale-holiday-mapping))


(defmethod is-holiday? :so
  [_ context]
  (holiday? context))