;; This file is autogenerated using vura.holidays.compile/-main

(ns vura.holidays.ua
  (:require 
  [clojure.string]
  [vura.holidays :refer [is-holiday?]]
  [vura.holidays.name :as n]
  [vura.holidays.compiler :as compiler]))


(def holidays
  {"julian 12-25 and if saturday, sunday then next monday"
 {"substitute" true, :name (partial n/get-name "julian 12-25")},
 "08-24 and if saturday, sunday then next monday"
 {"substitute" true, :name (partial n/get-name "Independence Day")},
 "05-09 and if saturday, sunday then next monday"
 {"substitute" true,
  :name
  {:uk "День перемоги над нацизмом у Другій світовій війні",
   :en "Victory Day"}},
 "05-01 and if saturday, sunday then next tuesday"
 {"substitute" true, :name (partial n/get-name "05-01")},
 "01-01 and if saturday, sunday then next tuesday"
 {"_name" "01-01", "substitute" true, :name {:en "New Year"}},
 "06-28 and if saturday, sunday then next monday"
 {"substitute" true, :name (partial n/get-name "Constitution Day")},
 "orthodox and if sunday then next monday"
 {:name (partial n/get-name "orthodox")},
 "05-02 and if saturday, sunday then next monday"
 {"substitute" true, :name (partial n/get-name "05-01")},
 "orthodox 49 and if sunday then next monday"
 {:name (partial n/get-name "easter 49")},
 "01-02 and if saturday, sunday then next monday"
 {"_name" "01-01", "substitute" true, :name {:en "New Year"}},
 "03-08 and if saturday, sunday then next monday"
 {:name (partial n/get-name "03-08")},
 "10-14 and if saturday, sunday then next monday"
 {"substitute" true,
  "active" [{"from" "2015-03-05"}],
  :name {:uk "День захисника України", :en "Defender of Ukraine Day"}}}
)


(def locale-holiday-mapping
  (reduce-kv
    (fn [result definition name-mapping]
      (assoc result
             (compiler/compile-type (compiler/parse-definition definition))
             name-mapping))
    nil
    holidays))


(defn holiday?
  [context]
  (some
   (fn [[pred naming]]
     (when (pred context)
       naming))
   locale-holiday-mapping))


(defmethod is-holiday? :ua
  [_ context]
  (holiday? context))