;; This file is autogenerated using vura.holidays.compile/-main

(ns vura.holidays.zw
  (:require 
  [clojure.string]
  [vura.holidays :refer [is-holiday?]]
  [vura.holidays.name :as n]
  [vura.holidays.compiler :as compiler]))


(def holidays
  {"2nd monday in August" {:name {:en "Heroes' Day"}},
 "01-01" {:name (partial n/get-name "01-01")},
 "3rd sunday in June"
 {"type" "observance", :name (partial n/get-name "Fathers Day")},
 "05-25" {:name {:en "Africa Day"}},
 "easter" {"type" "observance", :name (partial n/get-name "easter")},
 "easter -2" {:name (partial n/get-name "easter -2")},
 "2nd sunday in May"
 {"type" "observance", :name (partial n/get-name "Mothers Day")},
 "12-26" {:name (partial n/get-name "12-26")},
 "easter 1" {:name (partial n/get-name "easter 1")},
 "05-01" {:name (partial n/get-name "05-01")},
 "04-18" {:name (partial n/get-name "Independence Day")},
 "12-25" {:name (partial n/get-name "12-25")},
 "12-22" {:name {:en "Unity Day"}},
 "2nd tuesday in August" {:name {:en "Defence Forces Day"}}}
)


(def locale-holiday-mapping
  (reduce-kv
    (fn [result definition name-mapping]
      (assoc result
             (compiler/compile-type (compiler/parse-definition definition))
             name-mapping))
    nil
    holidays))


(defn holiday?
  [context]
  (some
   (fn [[pred naming]]
     (when (pred context)
       naming))
   locale-holiday-mapping))


(defmethod is-holiday? :zw
  [_ context]
  (holiday? context))